# system configuration
system:
  # service listening address
  port: 9090
  # file storage path
  storage-path: /tmp/fileserver/files

# logger configuration
log:
  # file path
  path: /tmp/fileserver/logs
  # file name
  name: fileserver.log
  # log level
  level: INFO