/**
 * 字节跳动图标库：https://iconpark.oceanengine.com/official
 * and vue3 https://github.com/bytedance/IconPark/tree/master/packages/vue-next
 * element-plus icon: https://element-plus.gitee.io/zh-CN/component/icon.html
 * @description 图标库按需注册
 * @author wcf
 * @example <icon-user theme="outline" size="16" fill="#999" />
 * @example <el-icon :size="20"> <edit /> </el-icon>
 */

// icon-park
import {
  AddText,
  Alipay,
  AllApplication,
  AudioFile,
  Back,
  ChartHistogram,
  ChartLine,
  Close,
  Code,
  Copy,
  FileExcel,
  FileMusic,
  FilePdf,
  FilePpt,
  FileTxt,
  FileWord,
  FileZip,
  FolderClose,
  FullScreen,
  Github,
  GoEnd,
  Google,
  GoStart,
  Home,
  ImageFiles,
  Like,
  LinkCloudFaild,
  LinkInterrupt,
  Lock,
  Mail,
  MenuFoldOne,
  MenuUnfoldOne,
  Minus,
  MoveOne,
  MultiPictureCarousel,
  MusicList,
  Next,
  OffScreen,
  PauseOne,
  Performance,
  Pic,
  Play,
  PlayCycle,
  PlayOnce,
  Refresh,
  Remind,
  ScanCode,
  Search,
  Tailoring,
  TailoringTwo,
  Theme,
  ToLeft,
  ToRight,
  Translate,
  Twitter,
  User,
  VideoFile,
  VolumeMute,
  VolumeNotice,
  Wechat,
  Xigua,
} from '@icon-park/vue-next';
import '@icon-park/vue-next/styles/index.css';
import SvgIcon from '/@/components/SvgIcon/index.vue';

// 所需的组件
export const components = [
  AddText,
  Alipay,
  AllApplication,
  AudioFile,
  Back,
  ChartHistogram,
  ChartLine,
  Close,
  Code,
  Copy,
  FileExcel,
  FileMusic,
  FilePdf,
  FilePpt,
  FileTxt,
  FileWord,
  FileZip,
  FolderClose,
  FullScreen,
  Github,
  GoEnd,
  Google,
  GoStart,
  Home,
  ImageFiles,
  Like,
  LinkCloudFaild,
  LinkInterrupt,
  Lock,
  Mail,
  MenuFoldOne,
  MenuUnfoldOne,
  Minus,
  MoveOne,
  MultiPictureCarousel,
  MusicList,
  Next,
  OffScreen,
  PauseOne,
  Performance,
  Pic,
  Play,
  PlayCycle,
  PlayOnce,
  Refresh,
  Remind,
  ScanCode,
  Search,
  Tailoring,
  TailoringTwo,
  Theme,
  ToLeft,
  ToRight,
  Translate,
  Twitter,
  User,
  VideoFile,
  VolumeMute,
  VolumeNotice,
  Wechat,
  Xigua,
];

// 注册
export default (app: any) => {
  app.component('svg-icon', SvgIcon);
  components.forEach((component) => {
    // app.component(component.name.replace('icon-', ''), component);
    app.component(component.name, component);
  });
};
